#!/bin/bash
#
#   JamesMiller - forked from @tschaffter
#
#   usage with podman/docker:
#   podman run --rm  -v ./output:/home/builder/output:Z \
#                       localhost/piharden:1.0 \
#                       --kernel-branch rpi-6.12.y \
#                       --kernel-localversion $(date '+%Y%m%d')-hardenedv \
#                       --arch arm64 --device rpiz2
#
#   Cross-compiles the Raspberry Pi kernel with SELinux support and other
#   hardening features enabled.
#
#   Example:
#
#   ./build-kernel.sh \
#       --kernel-branch rpi-6.12.y \
#       --kernel-localversion 6.12.y-20250607-hardened
#       --arch arm64
#       --device rpi4
#       --interactive
#   Notes:
#
#   - Identify kernel branch or tag from https://github.com/raspberrypi/linux
#   - Identify --kernel-defconfig value from https://www.raspberrypi.org/documentation/linux/kernel/building.md
#   - The value of --kernel-localversion will be returned by `uname -a`
#   - arch of either arm or arm64
#
# ARG_OPTIONAL_SINGLE([kernel-branch],[],[Kernel branch to build],[''])
# ARG_OPTIONAL_SINGLE([kernel-localversion],[],[Kernel local version],[''])
# ARG_HELP([The general script's help msg])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.8.1 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info
# Generated online by https://argbash.io/generate


die()
{
	local _ret=$2
	test -n "$_ret" || _ret=1
	test "$_PRINT_HELP" = yes && print_help >&2
	echo "$1" >&2
	exit ${_ret}
}


begins_with_short_option()
{
	local first_option all_short_options='h'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_kernel_branch=""
_arg_kernel_localversion=""
_arg_interactive=0
_arg_device=""
_arg_arch=""

print_help()
{
	printf '%s\n' "Cross-compiling hardened kernels for Raspberry Pi"
	printf 'Usage: %s [--kernel-branch <arg>] [--kernel-localversion <arg>] [--arch <arg>] [--device <arg>] [-h|--help]\n' "$0"
	printf '\t%s\n' "--kernel-branch: Kernel branch to build (default: '')"
        printf '\t%s\n' "--kernel-localversion: Kernel local version (default: '')"
        printf '\t%s\n' "--arch: arch ie arm64 or arm (default: '')"
        printf '\t%s\n' "--device: device shortcode, one of [rpi1,rpicm1,rpiz,rpi2,rpi3,rpiz2,rpi4,rpi400,rpicm4,rpi5]"
        printf '\t%s\n' "--interactive if present build config interactively"
        printf '\t%s\n' "-h, --help: Prints help"
}


parse_commandline()
{
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			--kernel-branch)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_kernel_branch="$2"
				shift
				;;
			--kernel-branch=*)
				_arg_kernel_branch="${_key##--kernel-branch=}"
				;;
                        --kernel-localversion)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_kernel_localversion="$2"
				shift
				;;
			--kernel-localversion=*)
                                _arg_kernel_localversion="${_key##--kernel-localversion=}"
				;;
                        --arch)
                                test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
                                _arg_arch="$2"
                                shift
                                ;;
                        --arch=*)
                                _arg_arch="${_key##--arch=}"
                                ;;
                        --device)
                                test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
                                _arg_device="$2"
                                shift
                                ;;
                        --device=*)
                                _arg_device="${_key##--device=}"
                                ;;
                        --interactive)
                                _arg_interactive=1
                                ;;
                        --interactive=*)
                                _arg_interactive=1
                                ;;
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			*)
				_PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
				;;
		esac
		shift
	done
}

parse_commandline "$@"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash

# The argument --kernel-branch must be specified.
if [ -z "$_arg_kernel_branch" ]; then
    echo "The argument --kernel-branch <arg> is missing."
    exit 1
fi

# The argument --kernel-localversion must be specified.
if [ -z "$_arg_kernel_localversion" ]; then
    echo "The argument --kernel-localversion <arg> is missing."
    exit 1
fi

# The argument --arch must be specified.
if [ -z "$_arg_arch" ]; then
    echo "The argument --arch <arg> is missing."
    exit 1
fi

# The argument --device must be specified.
if [ -z "$_arg_device" ]; then
    echo "The argument --device <device> is missing."
    exit 1
fi

echo "device is $_arg_device"

_workdir=$(pwd)
_tools_dir=$_workdir/tools
_kernel_src_dir=$_workdir/linux
_output_dir=/home/builder/output

# Check that the output directory exists and is writable
test -d $_output_dir || die "Output directory $_output_dir does not exist" 1
test -w $_output_dir || die "Output directory $_output_dir is not writable" 1


# Get the kernel source code
if [ -d $_kernel_src_dir ]; then
    echo "Using existing kernel source dir $_kernel_src_dir"
else
    echo "Getting kernel source code"
    git clone \
        --branch $_arg_kernel_branch \
        --depth=1 \
        https://github.com/raspberrypi/linux \
        $_kernel_src_dir \
        || die "Unable to clone kernel source code" 1
fi

if [ $_arg_arch == "arm64" ];then
   echo "64 bit"
   export CC=aarch64-linux-gnu-gcc
   export CXX=aarch64-linux-gnu-g++
   export $(dpkg-architecture -aarm64)
   export CROSS_COMPILE=aarch64-linux-gnu-
   case "$_arg_device" in
        rpi3) ;& 
        rpicm3) ;&
        rpicm4) ;&
        rpiz2) ;&
        rpi4) ;&
        rpi400) export KERNEL=kernel8 _arg_kernel_defconfig=bcm2711_defconfig
                 ;;
        rpi5)   export KERNEL=kernel_2712 _arg_kernel_defconfig=bcm2712_defconfig
                 ;;
        *) echo "incorrect device code - please select from one of rpi3,rpicm3,rpicm4,rpiz2,rpi4,rpi400,rpi5"; exit 1
   esac
else
   echo "32 bit"
   export CC=arm-linux-gnueabihf-gcc
   export CXX=arm-linux-gnueabihf-g++
   export $(dpkg-architecture -aarmhf)
   export CROSS_COMPILE=arm-linux-gnueabihf-
   case "$_arg_device" in
        rpi1) ;&
        rpicm1) ;&
        rpiz) export KERNEL=kernel _arg_kernel_defconfig=bcmrpi_defconfig
               ;;
        rpi2) ;&
        rpi3) ;&
        rpicm3) ;&
        rpiz2) export KERNEL=kernel7 _arg_kernel_defconfig=bcm2709_defconfig
                ;;
        rpi4) ;&
        rpi400) ;&
        rpicm4) export KERNEL=kernel7l _arg_kernel_defconfig=bcm2711_defconfig
                 ;;
        *) echo "incorrect device code - please select from one of rpi1,rpicm1,rpiz,rpi2,rpi3,rpicm3,rpiz2,rpi4,rpi400,rpicm4"; exit 1
   esac
fi

cd $HOME
# git clone https://github.com/a13xp0p0v/kernel-hardening-checker

cd $_kernel_src_dir

_kernel_version=$(make kernelversion)

echo "Kernel version is $_kernel_version"
echo "Kernel local version is $_arg_kernel_localversion"

echo "Cleaning up the directory"
make mrproper

echo "Creating initial .config defconfig is $_arg_kernel_defconfig"
make ARCH=$_arg_arch CROSS_COMPILE= $_arg_kernel_defconfig \
    || die "Unable to create initial .config" 1

# $HOME/kernel-hardening-checker/bin/kernel-hardening-checker -g ARM64 > harden_config
mkdir $HOME/new_config
./scripts/kconfig/merge_config.sh -m -O $HOME/new_config ./.config ./kernel/configs/hardening.config
mv .config .config_old
mv $HOME/new_config/.config $_kernel_src_dir/.config

echo "Setting kernel local version"
./scripts/config --set-str  CONFIG_LOCALVERSION "-$_arg_kernel_localversion"

echo "Enabling Audit"
./scripts/config --enable CONFIG_AUDIT
./scripts/config --enable CONFIG_AUDIT_LOGINUID_IMMUTABLE

echo "Enabling Security"
./scripts/config --enable CONFIG_SECURITY
./scripts/config --enable CONFIG_SECURITY_NETWORK

echo "Enabling SELinux"
./scripts/config --enable   CONFIG_SECURITY_SELINUX
./scripts/config --enable   CONFIG_SECURITY_SELINUX_BOOTPARAM
./scripts/config --set-val  CONFIG_SECURITY_SELINUX_BOOTPARAM_VALUE 1
./scripts/config --disable  CONFIG_SECURITY_SELINUX_DISABLE
./scripts/config --enable   CONFIG_SECURITY_SELINUX_DEVELOP
./scripts/config --enable   CONFIG_SECURITY_SELINUX_AVC_STATS
./scripts/config --set-val  CONFIG_SECURITY_SELINUX_CHECKREQPROT_VALUE 1
# ./scripts/config --disable  CONFIG_SECURITY_SELINUX_POLICYDB_VERSION_MAX
./scripts/config --enable   CONFIG_DEFAULT_SECURITY_SELINUX
./scripts/config --disable  CONFIG_DEFAULT_SECURITY_DAC
./scripts/config --set-str  CONFIG_DEFAULT_SECURITY "selinux"

# Validate config changes
if [ $_arg_interactive -eq 0 ];then
   make ARCH=$_arg_arch CROSS_COMPILE=$CROSS_COMPILE olddefconfig
elif [ $_arg_interactive -eq 1 ];then
    make ARCH=$_arg_arch CROSS_COMPILE=$CROSS_COMPILE menuconfig
fi

echo "Building kernel and generating .deb packages"
DEB_HOST_ARCH=${_arg_arch} make ARCH=${_arg_arch} CROSS_COMPILE=${CROSS_COMPILE} -j$(($(nproc)+1)) deb-pkg \
        || die "Unable to build or package kernel" 1

echo "Moving .deb packages to $_output_dir"
mv $_workdir/*.deb $_output_dir/

echo "Compressing kernel source to $_output_dir"
make clean
mv $_workdir/linux $_workdir/linux-source-${_kernel_version}-${_arg_kernel_localversion}+
tar cjf \
	$_output_dir/linux-source-${_kernel_version}-${_arg_kernel_localversion}+.tar.bz2 \
	$_workdir/linux-source-${_kernel_version}-${_arg_kernel_localversion}+


echo ""
echo "SUCCESS The kernel has been successfully packaged."
echo ""
echo "INSTALL"
echo "sudo dpkg -i linux-*-${_arg_kernel_localversion}*.deb"
echo "sudo sh -c \"echo 'kernel=vmlinuz-${_kernel_version}-${_arg_kernel_localversion}+' >> /boot/config.txt\""
echo "sudo reboot"
echo ""
echo "ENABLE SELinux"
echo "sudo apt-get install selinux-basics selinux-policy-default auditd"
echo "sudo sh -c \"sed -i '$ s/$/ selinux=1 security=selinux/' /boot/cmdline.txt\""
echo "sudo touch /.autorelabel"
echo "sudo reboot"
echo "sestatus"
echo ""
echo "INSTALL SOURCE (OPTIONAL)"
echo "tar xjf linux-source-${_kernel_version}-${_arg_kernel_localversion}+.tar.bz2 --directory /usr/src/"
echo "ln -s linux-source-${_kernel_version}-${_arg_kernel_localversion}+ /usr/src/linux"

# ] <-- needed because of Argbash
